#!/bin/sh
module="scullc"
device="scullc"

# invoke rmmod with all arguments we got
dmesg -C
rmmod $module $* || exit 1
dmesg | tee rmmod.out

# remove nodes
rm -f /dev/${device}[0-3] /dev/${device}

exit 0
